#!/bin/bash
# by Joshua Shaffer on September 29, 2016
# Run this script to test all of the chips in the current working directory.

# This must be a path to the HardwareSimulator.sh
# If you are using a relative path it will be realitive to the project
# directory that you are testing and not to this script file.
SIMULATOR='../../tools/HardwareSimulator.sh'

# Output coloring controll codes
bold=$(tput bold)
normal=$(tput sgr0)
red=$(tput setaf 1)
green=$(tput setaf 2)

ERR_LIST=""

for TEST_SCRIPT in *.tst
do
    CHIP_NAME=${TEST_SCRIPT%.tst}
    echo -en "Testing ${bold}$CHIP_NAME${normal} ... "
    ERR_MESSAGE="$($SIMULATOR $TEST_SCRIPT 2>&1)"
    
    if [ $? != 0 ]; then
        echo -e "${red}fail${normal}"
        ERR_LIST="$ERR_LIST${red}${bold}$CHIP_NAME${normal}\n$ERR_MESSAGE\n\n"
    else
        echo -e "${green}pass${normal}"
        rm $CHIP_NAME.out
    fi
done

if [ "$ERR_LIST" ]; then
    echo -en "\n${red}Failed Tests:${normal}\n$ERR_LIST"
    echo "If you are haveing difficulty debuging your hdl use the graphical Hardware Simulator. It will give you more information."
    exit 1
else
    echo -e "${green}All tests passed!${normal}"
    exit 0
fi
